"""
Re-runnable, idempotent sync: populate app-brain's `github_repo` + `environments`
({name, branch, url, coolify_app_uuid}) from LIVE Coolify (the authoritative source
for uuid / branch / fqdn), extending coverage beyond the hand-set booking record.

Coolify is read-only here; app-brain is the write target. Values come straight from
Coolify — never inferred. A value Coolify doesn't provide is left null (the consumer
fails safe on a null branch).

Usage
-----
  # Coolify creds + app-brain DB are resolved at runtime; nothing secret is tracked.
  export BWS_ACCESS_TOKEN=...                       # to fetch Coolify API tokens from BWS
  export DATABASE_URL=postgresql+asyncpg://...      # the PROD app-brain DB (write target)

  python scripts/sync_deployment_from_coolify.py              # DRY RUN (default) — prints diffs
  python scripts/sync_deployment_from_coolify.py --apply      # actually write to app-brain
  python scripts/sync_deployment_from_coolify.py --apps booking-assistant

Mapping: a Coolify application -> an app-brain app by `git_repository` (case-folded
owner/repo) first, FQDN-host fallback second. One app-brain app may map to several
Coolify apps (prod + preview) -> several environment records. Coolify apps that map to
nothing are logged, never invented. Compose/Flavor-C apps are Coolify *services*, not
applications, so they never appear here — reported as "not covered (service)" upstream.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.brains.app.repositories.apps import normalize_host  # noqa: E402

# BWS secret UUIDs for the Coolify API tokens (same as the drift pipeline).
COOLIFY_INSTANCES = {
    "prod": {
        "base": "http://coolify-1.devonwatkins.com",
        "bws_uuid": "bbd71f41-b7df-4ae9-8fdb-b41501447308",
    },
    "dev": {
        "base": "http://192.168.139.217:8000",
        "bws_uuid": "8a2e1e10-d67b-4382-bbf3-b4150178e2a8",
    },
}

_ENV_ORDER = ["prod", "preview", "staging", "dev"]


# --------------------------------------------------------------------------- #
# Pure helpers (unit-tested in tests/brains/test_coolify_sync.py)             #
# --------------------------------------------------------------------------- #


def derive_repo(git_repository: str | None) -> str | None:
    """Parse a Coolify `git_repository` to canonical 'Owner/Repo' (case preserved).

    Handles SSH (git@github.com:Owner/Repo.git), HTTPS
    (https://github.com/Owner/Repo.git), and the bare 'Owner/Repo' Coolify often
    stores. Returns None if it can't extract two path segments.

    >>> derive_repo("git@github.com:AlobarQuest/booking-system.git")
    'AlobarQuest/booking-system'
    >>> derive_repo("AlobarQuest/booking-system")
    'AlobarQuest/booking-system'
    """
    if not git_repository:
        return None
    s = git_repository.strip()
    if not s:
        return None
    scp = re.match(r"^[\w.+-]+@[\w.-]+:(.+)$", s)
    if scp:
        path = scp.group(1)
    else:
        url = re.match(r"^[a-zA-Z][\w+.-]*://(?:[^@/]+@)?[^/]+/(.+)$", s)
        path = url.group(1) if url else s  # bare 'owner/repo'
    path = path.strip("/")
    if path.endswith(".git"):
        path = path[: -len(".git")]
    parts = [p for p in path.split("/") if p]
    if len(parts) < 2:
        return None
    return f"{parts[0]}/{parts[1]}"


def _is_ip(host: str | None) -> bool:
    return bool(host) and bool(re.fullmatch(r"\d{1,3}(?:\.\d{1,3}){3}", host))


def _is_autogenerated(host: str | None) -> bool:
    """A Coolify auto-generated host (*.sslip.io or a bare IP) rather than a custom domain."""
    return bool(host) and (host.endswith(".sslip.io") or _is_ip(host))


def pick_fqdn(fqdn: str | None) -> str | None:
    """Choose the best URL from a Coolify `fqdn` (which may be comma-separated).

    Prefers a real custom domain over Coolify's auto-generated *.sslip.io / IP host,
    but falls back to the auto-generated one rather than dropping the env. Returns an
    https-normalized URL (scheme added if missing, trailing slash trimmed), or None.

    >>> pick_fqdn("https://x.sslip.io,https://preview.booking.devonwatkins.com")
    'https://preview.booking.devonwatkins.com'
    """
    if not fqdn:
        return None
    candidates = []
    for raw in fqdn.split(","):
        raw = raw.strip()
        if not raw:
            continue
        url = raw if "://" in raw else f"https://{raw}"
        url = url.rstrip("/")
        candidates.append((url, normalize_host(url)))
    if not candidates:
        return None
    for url, host in candidates:
        if host and not _is_autogenerated(host):
            return url
    return candidates[0][0]


def _env_name(branch: str | None, host: str | None) -> str:
    if branch == "preview" or (host and host.startswith("preview.")):
        return "preview"
    return "prod"


def build_environment(coolify_app: dict) -> dict:
    """Build one {name, branch, url, coolify_app_uuid} record from a Coolify app.

    Exact contract shape (keeps the migration's array CHECK and the resolver happy).
    branch/url are exactly what Coolify reports (may be null) — never guessed.
    """
    url = pick_fqdn(coolify_app.get("fqdn"))
    host = normalize_host(url)
    branch = coolify_app.get("git_branch") or None
    return {
        "name": _env_name(branch, host),
        "branch": branch,
        "url": url,
        "coolify_app_uuid": coolify_app.get("uuid"),
    }


def map_coolify_to_app(
    coolify_apps: list[dict], appbrain_apps: list[dict]
) -> tuple[dict, list[dict]]:
    """Map Coolify applications onto app-brain apps.

    Returns (computed, unmapped):
      computed: {slug: {"github_repo": str|None, "environments": [records...]}}
      unmapped: Coolify apps that matched no app-brain record (logged, not invented).

    Match by git_repository (case-folded) first, then FQDN host (against an app's
    deployment_url host or any existing environment url host).
    """
    by_repo: dict[str, str] = {}
    by_host: dict[str, str] = {}
    for a in appbrain_apps:
        if a.get("github_repo"):
            by_repo.setdefault(a["github_repo"].lower(), a["slug"])
        h = normalize_host(a.get("deployment_url"))
        if h:
            by_host.setdefault(h, a["slug"])
        for e in a.get("environments") or []:
            eh = normalize_host(e.get("url"))
            if eh:
                by_host.setdefault(eh, a["slug"])

    computed: dict[str, dict] = {}
    unmapped: list[dict] = []
    for c in coolify_apps:
        repo = derive_repo(c.get("git_repository"))
        # A repo is trustworthy as github_repo ONLY if it matched an app-brain app.
        # dockerimage apps report a placeholder git_repository ("coollabsio/coolify")
        # and map via fqdn — never let that placeholder become a github_repo.
        matched_by_repo = bool(repo and repo.lower() in by_repo)
        slug = by_repo.get(repo.lower()) if repo else None
        if not slug:
            host = normalize_host(pick_fqdn(c.get("fqdn")))
            slug = by_host.get(host) if host else None
        if not slug:
            unmapped.append(
                {
                    "uuid": c.get("uuid"),
                    "name": c.get("name"),
                    "git_repository": c.get("git_repository"),
                    "fqdn": c.get("fqdn"),
                    "instance": c.get("instance"),
                }
            )
            continue
        entry = computed.setdefault(slug, {"github_repo": None, "environments": []})
        if matched_by_repo and not entry["github_repo"]:
            entry["github_repo"] = repo
        entry["environments"].append(build_environment(c))

    for entry in computed.values():
        entry["environments"].sort(
            key=lambda e: (
                _ENV_ORDER.index(e["name"]) if e["name"] in _ENV_ORDER else len(_ENV_ORDER),
                e["name"],
            )
        )
    return computed, unmapped


# --------------------------------------------------------------------------- #
# Coolify fetch (read-only) + DB write                                         #
# --------------------------------------------------------------------------- #


def _bws_get(uuid: str) -> str:
    # `--color no` is REQUIRED, not cosmetic. bws 2.0.0 emits ANSI escapes into
    # stdout even when stdout is not a TTY, so json.loads() fails on byte 0 with
    # "Expecting value" and the run dies before it reaches Coolify at all. It
    # honours neither NO_COLOR nor the absence of a terminal; only this flag, and
    # only before the subcommand. Symptom is a JSONDecodeError with no mention of
    # colour anywhere in it.
    out = subprocess.run(
        ["bws", "--color", "no", "secret", "get", uuid],
        capture_output=True,
        text=True,
        timeout=30,
    )
    if out.returncode != 0:
        raise SystemExit(f"bws secret get {uuid} failed: {out.stderr.strip()}")
    return json.loads(out.stdout)["value"]


def fetch_coolify_apps() -> list[dict]:
    """List applications across both Coolify instances. Read-only."""
    import httpx

    apps: list[dict] = []
    for instance, cfg in COOLIFY_INSTANCES.items():
        token = _bws_get(cfg["bws_uuid"])
        try:
            resp = httpx.get(
                f"{cfg['base']}/api/v1/applications",
                headers={"Authorization": f"Bearer {token}"},
                timeout=30,
            )
            resp.raise_for_status()
        except Exception as exc:  # noqa: BLE001
            print(f"  [warn] {instance} Coolify unreachable, skipping: {exc}")
            continue
        for a in resp.json():
            apps.append(
                {
                    "uuid": a.get("uuid"),
                    "name": a.get("name"),
                    "git_repository": a.get("git_repository"),
                    "git_branch": a.get("git_branch"),
                    "fqdn": a.get("fqdn"),
                    "instance": instance,
                }
            )
    return apps


async def _load_appbrain(conn) -> list[dict]:
    from sqlalchemy import text

    rows = (
        await conn.execute(
            text("SELECT slug, github_repo, deployment_url, environments FROM apps ORDER BY slug")
        )
    ).all()
    return [
        {
            "slug": r.slug,
            "github_repo": r.github_repo,
            "deployment_url": r.deployment_url,
            "environments": r.environments,
        }
        for r in rows
    ]


async def _run(apply: bool, only: set[str] | None) -> None:
    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        raise SystemExit("DATABASE_URL env var is required")

    print("Fetching Coolify applications (read-only)…")
    coolify_apps = fetch_coolify_apps()
    print(f"  {len(coolify_apps)} Coolify applications across instances")

    engine = create_async_engine(database_url)
    changed = 0
    async with engine.connect() as conn:
        appbrain = await _load_appbrain(conn)
        current = {a["slug"]: a for a in appbrain}
        computed, unmapped = map_coolify_to_app(coolify_apps, appbrain)

        print(f"\n{'APPLY' if apply else 'DRY RUN'} — per-app diff:")
        for slug in sorted(computed):
            if only and slug not in only:
                continue
            new = computed[slug]
            cur = current.get(slug, {})
            cur_repo, cur_envs = cur.get("github_repo"), cur.get("environments") or []
            # github_repo is gap-fill only: write it solely when currently null (never
            # overwrite/case-churn an existing value). environments is Coolify-authoritative.
            repo_fill = bool(new["github_repo"]) and not cur_repo
            envs_changed = new["environments"] != cur_envs
            mark = "~" if (repo_fill or envs_changed) else "="
            print(f"  [{mark}] {slug}")
            if repo_fill:
                print(f"        github_repo: {cur_repo!r} -> {new['github_repo']!r}  (fill)")
            print(
                f"        environments: {len(cur_envs)} -> {len(new['environments'])} "
                f"{[(e['name'], e['branch'], e['coolify_app_uuid']) for e in new['environments']]}"
            )
            if apply and (repo_fill or envs_changed):
                sets = ["environments = CAST(:envs AS jsonb)"]
                params = {"slug": slug, "envs": json.dumps(new["environments"])}
                if repo_fill:
                    sets.append("github_repo = :gh")
                    params["gh"] = new["github_repo"]
                await conn.execute(
                    text(f"UPDATE apps SET {', '.join(sets)} WHERE slug = :slug"), params
                )
                changed += 1

        if apply:
            await conn.commit()

        print(f"\nUnmapped Coolify apps (no app-brain record — NOT invented): {len(unmapped)}")
        for u in unmapped:
            print(f"  - {u['instance']}:{u['name']} repo={u['git_repository']} fqdn={u['fqdn']}")
        empty = [a["slug"] for a in appbrain if a["slug"] not in computed]
        print(f"\napp-brain apps with no Coolify mapping (left unchanged): {len(empty)}")
        print(f"  {', '.join(empty)}")

    await engine.dispose()
    print(
        f"\n{'Wrote ' + str(changed) + ' app(s).' if apply else 'Dry run — no writes. Re-run with --apply to write.'}"
    )


def main() -> None:
    p = argparse.ArgumentParser(description="Sync app-brain deployment fields from live Coolify")
    p.add_argument("--apply", action="store_true", help="write to app-brain (default is dry-run)")
    p.add_argument("--apps", help="comma-separated slugs to restrict to")
    args = p.parse_args()
    only = {s.strip() for s in args.apps.split(",")} if args.apps else None
    asyncio.run(_run(apply=args.apply, only=only))


if __name__ == "__main__":
    main()
